name: Actions Workflow

on: [push]

jobs:
  run-github-action:
    runs-on: ubuntu-latest
    steps:
      - name: Lista arquivos
        run: |
          pwd
          ls 
      - name: Checkout
        uses: actions/checkout@v3
      - name: Lista arquivos depois do Checkout
        run: |
          pwd
          ls -la
          echo $GITHUB_SHA
          echo $GITHUB_REPOSITORY
          echo $GITHUB_WORKSPACE
          echo "${{ github.token }}"
          git clone git@github.com:$GITHUB_REPOSITORY
          git checkout $GITHUB_SHA
      - name: JS Action Simples
        id: greet
        uses: actions/hello-world-javascript-action@v1
        with:
          who-to-greet: 'Seraph777'
      - name: Log Greeting time
        run: echo "${{ steps.greet.outputs.time }}" 
