name: Actions Workflow

on: [push]

jobs:
  run-github-action:
    runs-on: ubuntu-latest
    steps:
      - name: JS Action Simples
        id: grret
        uses: actions/hello-world-javascript-action@v1
        with:
          who-to-greet: 'Seraph777'
      - name: Log Greeting time
        run: echo "${{ steps.greet.outputs.time }}" 
